name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 18.x
      CAP_V: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Use npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --legacy-peer-deps
          fi

      - name: Build web
        run: npm run build

      # ---------- Capacitor príprava ----------
      - name: Ensure Capacitor deps
        run: |
          set -e
          NEED=0
          npm ls @capacitor/core >/dev/null 2>&1 || NEED=1
          npm ls @capacitor/android >/dev/null 2>&1 || NEED=1
          npm ls @capacitor/cli >/dev/null 2>&1 || NEED=1
          if [ "$NEED" = "1" ]; then
            npm i -D @capacitor/core@${CAP_V} @capacitor/android@${CAP_V} @capacitor/cli@${CAP_V}
          fi

      - name: Ensure capacitor.config.json
        run: |
          if [ ! -f "capacitor.config.json" ] && [ ! -f "capacitor.config.ts" ] && [ ! -f "capacitor.config.js" ]; then
            printf '%s\n' \
            '{' \
            '  "appId": "com.matt.intolerancies",' \
            '  "appName": "radka-scanner-plus",' \
            '  "webDir": "dist",' \
            '  "bundledWebRuntime": false,' \
            '  "server": { "androidScheme": "https" },' \
            '  "plugins": { "SplashScreen": { "launchShowDuration": 0 } }' \
            '}' > capacitor.config.json
          fi
          cat capacitor.config.json

      - name: Add Android platform if missing
        run: |
          if [ ! -d "android" ]; then
            npx --yes cap add android --skip-deps
          fi

      - name: Sync Capacitor (Android)
        run: npx --yes cap sync android

      - name: Patch AndroidManifest (CAMERA permission)
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if [ -f "$MANIFEST" ]; then
            grep -q 'android.permission.CAMERA' "$MANIFEST" || \
              sed -i '/<application/i\    <uses-permission android:name="android.permission.CAMERA" />' "$MANIFEST"
            grep -q 'android.hardware.camera' "$MANIFEST" || \
              sed -i '/<application/i\    <uses-feature android:name="android.hardware.camera" android:required="false" />' "$MANIFEST"
          fi

      # ---------- Java & Android SDK ----------
      - name: Setup Java 17 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
