name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '18.x'
      CAP_CLI_VERSION: '5'
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm ci --legacy-peer-deps || npm i --legacy-peer-deps
          else
            npm i --legacy-peer-deps
          fi

      # Doinštaluj Capacitor balíčky, ak chýbajú (bezpečné opakovane)
      - name: Ensure Capacitor deps
        run: |
          npm ls @capacitor/core >/dev/null 2>&1 || npm i @capacitor/core@${{ env.CAP_CLI_VERSION }} -E
          npm ls @capacitor/android >/dev/null 2>&1 || npm i @capacitor/android@${{ env.CAP_CLI_VERSION }} -E

      # Build webu (aby existoval dist/)
      - name: Build web
        run: npm run build

      # Inicializácia Capacitor (ak chýba config)
      - name: Capacitor init if missing
        run: |
          if [ ! -f "capacitor.config.ts" ] && [ ! -f "capacitor.config.json" ] && [ ! -f "capacitor.config.js" ]; then
            npx --yes @capacitor/cli@${{ env.CAP_CLI_VERSION }} capacitor init radka-scanner-plus com.matt.intolerancies --web-dir=dist --npm-client=npm --yes
          fi

      # Pridaj Android platformu, ak chýba
      - name: Add Android platform if missing
        run: |
          if [ ! -d "android" ]; then
            npx --yes @capacitor/cli@${{ env.CAP_CLI_VERSION }} capacitor add android
          fi

      # Sync (skopíruje dist/ do android projektu a upraví configy)
      - name: Capacitor sync (android)
        run: npx --yes @capacitor/cli@${{ env.CAP_CLI_VERSION }} capacitor sync android

      # ----- Java & Android SDK -----
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT"
          curl -fsSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmd-tools.zip
          unzip -q cmd-tools.zip -d "$ANDROID_SDK_ROOT"
          rm -f cmd-tools.zip
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv "$ANDROID_SDK_ROOT/cmdline-tools"/* "$ANDROID_SDK_ROOT/cmdline-tools/latest" || true
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_SDK_ROOT/tools/bin" >> $GITHUB_PATH

      - name: Accept licenses & install packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # ----- Build APK -----
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build debug APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
