name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 18.x

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --legacy-peer-deps
          fi

      - name: Build web
        run: npm run build

      # Vytvorí capacitor.config.json iba ak chýba
      - name: Ensure capacitor.config.json
        shell: bash
        run: |
          if [ ! -f "capacitor.config.json" ] && [ ! -f "capacitor.config.ts" ] && [ ! -f "capacitor.config.js" ]; then
            cat > capacitor.config.json <<'EOF'
            {
              "appId": "com.matt.intolerancies",
              "appName": "radka-scanner-plus",
              "webDir": "dist",
              "bundledWebRuntime": false,
              "server": { "androidScheme": "https" },
              "plugins": {
                "SplashScreen": { "launchShowDuration": 0 }
              }
            }
EOF
            echo "Created capacitor.config.json"
          else
            echo "Capacitor config already exists."
          fi

      - name: Add Android platform if missing
        shell: bash
        run: |
          if [ ! -d "android" ]; then
            npx --yes @capacitor/cli@5 cap add android
          else
            echo "Android platform already present."
          fi

      - name: Sync Capacitor (Android)
        run: npx --yes @capacitor/cli@5 cap sync android

      # Doplnenie CAMERA povolenia – idempotentne
      - name: Ensure CAMERA permission
        shell: bash
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if [ -f "$MANIFEST" ]; then
            if ! grep -q 'android.permission.CAMERA' "$MANIFEST"; then
              # vloží uses-permission hneď za prvý riadok <manifest ...>
              awk '{
                print $0;
                if ($0 ~ /<manifest/ && !ins) {
                  print "    <uses-permission android:name=\"android.permission.CAMERA\" />";
                  ins=1
                }
              }' "$MANIFEST" > "$MANIFEST.tmp" && mv "$MANIFEST.tmp" "$MANIFEST"
              echo "Added CAMERA permission."
            else
              echo "CAMERA permission already present."
            fi
          else
            echo "AndroidManifest.xml not found"
            exit 1
          fi

      # Java 17 pre Gradle
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK & licencie
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
